In [1]:
import tensorflow as tf

# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Print dataset shapes
print("Training data shape:", x_train.shape)  # (50000, 32, 32, 3)
print("Training labels shape:", y_train.shape)  # (50000, 1)
print("Test data shape:", x_test.shape)  # (10000, 32, 32, 3)
print("Test labels shape:", y_test.shape)  # (10000, 1)


170498071/170498071 [==============================] - 45s 0us/step
Training data shape: (50000, 32, 32, 3)
Training labels shape: (50000, 1)
Test data shape: (10000, 32, 32, 3)
Test labels shape: (10000, 1)


In [2]:
# Print the first 5 rows of the training data
print(x_train[:5])

# Print the first 5 labels of the training data
print(y_train[:5])

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [4]:
#preprocessing data
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [6]:
# Convolutional Neural Network using 2 layers of conv2D and then giving the output to a dense layer
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(tf.keras.layers.MaxPooling2D((2, 2)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Conv2D(64, (3, 3), activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.MaxPooling2D((2, 2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=64)

# Evaluate the model
model.evaluate(x_test, y_test)

#1st output =  [0.9055706858634949, 0.7009999752044678] # 70.1% accuracy


Epoch 1/10
782/782 [==============================] - 74s 81ms/step - loss: 1.5875 - accuracy: 0.4226
Epoch 2/10
782/782 [==============================] - 59s 76ms/step - loss: 1.2420 - accuracy: 0.5613
Epoch 3/10
782/782 [==============================] - 61s 78ms/step - loss: 1.0990 - accuracy: 0.6150
Epoch 4/10
782/782 [==============================] - 59s 75ms/step - loss: 1.0222 - accuracy: 0.6422
Epoch 5/10
782/782 [==============================] - 60s 76ms/step - loss: 0.9661 - accuracy: 0.6650
Epoch 6/10
782/782 [==============================] - 57s 73ms/step - loss: 0.9248 - accuracy: 0.6791
Epoch 7/10
782/782 [==============================] - 53s 67ms/step - loss: 0.8889 - accuracy: 0.6913
Epoch 8/10
782/782 [==============================] - 55s 70ms/step - loss: 0.8594 - accuracy: 0.7010
Epoch 9/10
782/782 [==============================] - 52s 67ms/step - loss: 0.8362 - accuracy: 0.7092
Epoch 10/10
313/313 [==============================] - 5s 14ms/step - loss: 0.9053

[0.9053444266319275, 0.6868000030517578]